import mongoose, { Schema, Document, Types } from 'mongoose'
import {
  PRINT_ORDER_STATUSES,
  PRINT_MATERIALS,
  type PrintOrderStatus,
  type PrintMaterial,
  type PrintPriority,
  type DeliveryMethod,
  type PaymentMethod,
  type PaymentStatus,
} from '@/lib/print-enums'

// Re-export so server-side callers (API routes) can keep importing from here.
export {
  PRINT_ORDER_STATUSES,
  PRINT_MATERIALS,
}
export type {
  PrintOrderStatus,
  PrintMaterial,
  PrintPriority,
  DeliveryMethod,
  PaymentMethod,
  PaymentStatus,
}

export interface IPrintFile {
  url: string                  // Cloudinary secure_url
  publicId?: string            // Cloudinary public_id (for deletion)
  fileName: string
  fileFormat: 'stl' | 'obj'
  sizeBytes: number
}

export interface IPrintItem {
  _id?: Types.ObjectId         // auto-generated by Mongoose (PrintItemSchema has _id: true)
  file: IPrintFile
  material: PrintMaterial
  color: string                // hex or named, e.g. "#ff5500" or "red"
  layerHeightMm: 0.12 | 0.20 | 0.28
  infillPct: number            // 10..100
  quantity: number
  priority: PrintPriority
  // Estimates (set by admin or auto-quote later)
  estWeightG?: number
  estTimeMin?: number
  /** Mesh volume in cm³, computed client-side at upload — used for re-estimating
   *  the price on the admin side and as a starting point for phase-2 slicer integration. */
  volumeCm3?: number
  /** Mesh surface area in cm², computed client-side. Drives the shell-area weight model. */
  surfaceAreaCm2?: number
  /** Per-unit estimate the customer was shown at submit time (pre-admin-quote). */
  customerEstimateUnitPrice?: number
  // Pricing
  unitPrice?: number           // THB; admin-set for MVP
  lineTotal?: number           // unitPrice * quantity
  adminOverride: boolean       // true if admin set price manually (always true in MVP)
  notes?: string               // admin-only notes per item ("needs support", etc.)
}

export interface IShippingAddress {
  recipient: string
  phone: string
  line1: string
  line2?: string
  district?: string
  province: string
  postalCode: string
}

export interface IStatusEntry {
  status: PrintOrderStatus
  changedBy?: string           // clerkUserId or 'system' or 'admin'
  reason?: string
  changedAt: Date
}

export interface IPaymentInfo {
  method?: PaymentMethod
  status: PaymentStatus
  amount?: number
  // PromptPay
  qrPayload?: string           // raw EMVCo string (regenerable)
  // Bank transfer / slip
  slipUrl?: string             // Cloudinary URL
  slipUploadedAt?: Date
  verifiedBy?: string          // admin clerkUserId
  verifiedAt?: Date
  rejectReason?: string
}

export interface IPrintOrder extends Document {
  orderNumber: string                   // PR-YYYYMM-XXXXX
  clerkUserId?: string                  // Clerk auth id; optional for guest flow later
  customerName: string                  // denormalized snapshot
  customerPhone: string
  customerEmail?: string

  status: PrintOrderStatus
  statusHistory: IStatusEntry[]

  items: IPrintItem[]
  subtotal: number                      // sum of line totals (THB)
  shippingFee: number
  discount: number
  total: number
  currency: string                      // 'THB'

  deliveryMethod: DeliveryMethod
  shippingAddress?: IShippingAddress
  trackingNumber?: string

  payment: IPaymentInfo

  notesCustomer?: string
  notesAdmin?: string

  quotedBy?: string                     // admin clerkUserId
  quotedAt?: Date
  paidAt?: Date
  completedAt?: Date

  createdAt: Date
  updatedAt: Date
}

const PrintFileSchema = new Schema<IPrintFile>(
  {
    url: { type: String, required: true },
    publicId: { type: String },
    fileName: { type: String, required: true },
    fileFormat: { type: String, enum: ['stl', 'obj'], required: true },
    sizeBytes: { type: Number, required: true },
  },
  { _id: false }
)

const PrintItemSchema = new Schema<IPrintItem>(
  {
    file: { type: PrintFileSchema, required: true },
    material: { type: String, enum: PRINT_MATERIALS, required: true },
    color: { type: String, required: true },
    layerHeightMm: { type: Number, enum: [0.12, 0.20, 0.28], required: true },
    infillPct: { type: Number, min: 10, max: 100, required: true },
    quantity: { type: Number, min: 1, required: true },
    priority: { type: String, enum: ['standard', 'express'], default: 'standard' },
    estWeightG: { type: Number },
    estTimeMin: { type: Number },
    volumeCm3: { type: Number },
    surfaceAreaCm2: { type: Number },
    customerEstimateUnitPrice: { type: Number },
    unitPrice: { type: Number },
    lineTotal: { type: Number },
    adminOverride: { type: Boolean, default: false },
    notes: { type: String },
  },
  { _id: true }
)

const ShippingAddressSchema = new Schema<IShippingAddress>(
  {
    recipient: { type: String, required: true },
    phone: { type: String, required: true },
    line1: { type: String, required: true },
    line2: { type: String },
    district: { type: String },
    province: { type: String, required: true },
    postalCode: { type: String, required: true },
  },
  { _id: false }
)

const StatusEntrySchema = new Schema<IStatusEntry>(
  {
    status: { type: String, enum: PRINT_ORDER_STATUSES, required: true },
    changedBy: { type: String },
    reason: { type: String },
    changedAt: { type: Date, default: Date.now },
  },
  { _id: false }
)

const PaymentInfoSchema = new Schema<IPaymentInfo>(
  {
    method: { type: String, enum: ['promptpay', 'bank_transfer'] },
    status: { type: String, enum: ['pending', 'submitted', 'verified', 'rejected'], default: 'pending' },
    amount: { type: Number },
    qrPayload: { type: String },
    slipUrl: { type: String },
    slipUploadedAt: { type: Date },
    verifiedBy: { type: String },
    verifiedAt: { type: Date },
    rejectReason: { type: String },
  },
  { _id: false }
)

const PrintOrderSchema = new Schema<IPrintOrder>(
  {
    orderNumber: { type: String, required: true, unique: true, index: true },
    clerkUserId: { type: String, index: true },
    customerName: { type: String, required: true },
    customerPhone: { type: String, required: true },
    customerEmail: { type: String },

    status: { type: String, enum: PRINT_ORDER_STATUSES, default: 'pending_review', index: true },
    statusHistory: { type: [StatusEntrySchema], default: [] },

    items: { type: [PrintItemSchema], required: true },
    subtotal: { type: Number, default: 0 },
    shippingFee: { type: Number, default: 0 },
    discount: { type: Number, default: 0 },
    total: { type: Number, default: 0 },
    currency: { type: String, default: 'THB' },

    deliveryMethod: { type: String, enum: ['pickup', 'kerry', 'flash', 'ems'], required: true },
    shippingAddress: { type: ShippingAddressSchema },
    trackingNumber: { type: String },

    payment: { type: PaymentInfoSchema, default: () => ({ status: 'pending' }) },

    notesCustomer: { type: String },
    notesAdmin: { type: String },

    quotedBy: { type: String },
    quotedAt: { type: Date },
    paidAt: { type: Date },
    completedAt: { type: Date },
  },
  { timestamps: true }
)

// Compound index for admin worklist (most common query: filter by status, sort by recency)
PrintOrderSchema.index({ status: 1, createdAt: -1 })

// Generates a human-readable order number: PR-YYYYMM-XXXXX (base36, time-derived)
// Practically unique for MVP volumes; the unique index on orderNumber is the safety net.
export function generateOrderNumber(): string {
  const now = new Date()
  const yyyymm = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}`
  const suffix = Date.now().toString(36).slice(-5).toUpperCase()
  return `PR-${yyyymm}-${suffix}`
}

const PrintOrder =
  (mongoose.models.PrintOrder as mongoose.Model<IPrintOrder>) ||
  mongoose.model<IPrintOrder>('PrintOrder', PrintOrderSchema)

export default PrintOrder
export type { Types as MongooseTypes }
